// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjxcogdenkkfgyqnpcza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qeGNvZ2RlbmtrZmd5cW5wY3phIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMjYwMDcsImV4cCI6MjA3MTYwMjAwN30.kKLpkwq6XZjN0av_Col7KXXofruFq0oCaRUIzmt8P6I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});